### ISSUE TITLE
genome base frequencies are not averaged

### ISSUE THREAD

**Issue by balabanmetin** [nishatbristy007/SkmerExtended_Tool#5]
https://github.com/nishatbristy007/SkmerExtended_Tool/blob/f6dd05446322f679abbe9445927eff135a09fa1a/Tool_rand_match.py#L356

We should average them as stated in the commend in line 356.

**Comment by nishatbristy007** [comment]
Modified w here:

https://github.com/nishatbristy007/SkmerExtended_Tool/blob/f442e260cf5d80a547637a32ac3a5c605d93f4a9/Tool_rand_match.py#L268-L270
