### ISSUE TITLE
estimation of w and L for genome skims

### ISSUE THREAD

**Issue by balabanmetin** [nishatbristy007/SkmerExtended_Tool#6]
https://github.com/nishatbristy007/NSB/blob/6ca5f0e2041a4690ee62936fc4ca22938b3bfaac/jaccard_estimator_jf_free.py#L382-L391

should be the following

```
    w1 = (freqs_1[0]+freqs_1[3])/freqs_1[4]
    w2 = (freqs_2[0]+freqs_2[3])/freqs_2[4]
    if fl==0:
        L1 = freqs_1[4]
        L2 = freqs_2[4]
    else:
        L1 = 2*l1
        L2 = 2*l2
```

**Comment by balabanmetin** [comment]
https://github.com/nishatbristy007/NSB/blob/6ca5f0e2041a4690ee62936fc4ca22938b3bfaac/NSB_jf_free.py#L416-L426

should be the following 

```
     f = self.freqs[i] if self.freqs[i][4] > self.freqs[j][4] else self.freqs[j] #(freq[i]+freq[j])/2 
     f /= f[4] 
     f1=self.freqs[i]/self.freqs[i][4] 
     f2=self.freqs[j]/self.freqs[j][4] 
```

no need to use the estimated length here. so no need for if/else.  f values are calculated the same way, assembly or reads, doesn't matter.

**Comment by nishatbristy007** [comment]
Thanks, Metin. I've updated the code according to your comments.
